name: Daily Job Scraper & Notifier

on:
  schedule:
    - cron: '0 8 * * *'  # runs daily at 08:00 UTC
  workflow_dispatch:

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run cron script
        run: npm run cron
        env:
          NEXT_PUBLIC_SUPABASE_URL:  ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY:  ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          GROQ_API_KEY:  ${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL:    ${{ secrets.GROQ_MODEL }}
          EMAIL_HOST:    ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT:    ${{ secrets.EMAIL_PORT }}
          EMAIL_USER:    ${{ secrets.EMAIL_USER }}
          EMAIL_PASS:    ${{ secrets.EMAIL_PASS }}
          NOTIFY_EMAIL:  ${{ secrets.NOTIFY_EMAIL }}
